name: Dynamic references in workflow files for different environments in your Mule application

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  deploy-api:
    runs-on: ubuntu-latest
    steps:
      - name: actions/chechout
        uses: actions/checkout@v4
        
      - name: Choose environment
        run: echo "Deploying to ${{ inputs.environment }} environment"
        
      - name: print event_name ${{ github.event_name }}
        run: echo "Deploying to ${{ github.event_name }} name."
        
      # - name: Dispatch deployment job
      #   if: ${{ github.event_name == 'push' }}
      #   uses: ./.github/workflows/dispatch-deployment.yml
      #   with:
      #     environment: ${{ inputs.environment }}
