name: Dynamic references in workflow files for different environments in your Mule application

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  deploy-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Choose environment
        run: echo "Deploying to ${{ inputs.environment }} environment"
        
      - name: Print event name
        run: echo "Deploying to ${{ github.event_name }} event."
        
      - name: Dispatch deployment job
        if: ${{ github.event_name == 'push' }}
        uses: ./.github/workflows/dispatch-deployment.yml
        with:
          environment: ${{ inputs.environment }}
