name: Main Configuration file for orchestration of pipeline

on:
  workflow_call:

jobs:
  Run-Tests:
    if: ${{ GITHUB.event_name == 'pull_request' }}
    uses: ./.github/workflows/deploy-dev.yml@main
    secrets: inherit
